# Generated by Django 4.2.6 on 2023-10-28 19:27

from django.db import migrations
import random

def add_barcode(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    all_products = Product.objects.all()

    barcodes = random.sample(
        range(100000000, 999999999),
        len(all_products)
    )
    for x in range(len(all_products)):
        current_product = all_products[x]
        current_product.barcode = barcodes[x]
        current_product.save()

def reverse_add_barcode(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    for product in Product.object.all():
        product.barcode = 0
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_add_barcode)
    ]
